apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:v2.15.0@sha256:aa10e84da624f65be107f9317dbf6e212fa812e0ebf62e74d032d0762eccc930
          resources: {}
          imagePullPolicy: Always
          command: ["ntfy", "serve"]
          envFrom:
            - configMapRef:
                name: ntfy-server-config
          ports:
            - containerPort: 80
          volumeMounts:
            - name: user-db
              mountPath: "/var/lib/ntfy"
          initContainers:
            - name: init-user-db
              image: binwiederhier/ntfy:v2.15.0@sha256:aa10e84da624f65be107f9317dbf6e212fa812e0ebf62e74d032d0762eccc930
              imagePullPolicy: Always
              command: ["/bin/sh", "-c"]
              args:
                - |
                  ntfy serve &
                  if [ $? -eq 0 ]; then
                    while true; do sleep 3 && test -f $NTFY_AUTH_FILE && break; done
                    ntfy user add --role=admin $NTFY_USERNAME
                    pkill -TERM ntfy
                  else
                    exit $?
                  fi
              envFrom:
                - configMapRef:
                    name: ntfy-server-config
                - secretRef:
                    name: ntfy-user-config
              volumeMounts:
                - mountPath: /var/lib/ntfy/
                  name: user-db
      volumes:
        - name: user-db
          persistentVolumeClaim:
            claimName: ntfy-pvc
