---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shadow-empire-pbem-bot-3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shadow-empire-pbem-bot-secrets-3
    template:
      engineVersion: v2
      data:
        # App
        USER_MAPPINGS: "{{ .user_mappings }}"
        GAME_NAME: "{{ .game_name }}"
        DISCORD_WEBHOOK_URL: "{{ .discord_webhook_url }}"
        WATCH_DIRECTORY: "{{ .watch_directory }}"
        IGNORE_PATTERNS: "{{ .ignore_patterns }}"
        REMINDER_INTERVAL_MINUTES: "{{ .reminder_interval_minutes }}"
  dataFrom:
    - extract:
        key: shadow-empire-pbem-bot-3
