---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: libation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: libation-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AccountsSettings.json: |
          {{ .LIBATION_ACCOUNTS_SETTINGS | toString }}
  dataFrom:
    - extract:
        key: libation