---
sonarr:
  series-1080p:
    base_url: http://sonarr.home-media.svc.cluster.local:8080
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      episodes:
        rename: true
        anime: default
        daily: default
        standard: default
      season: default
      series: jellyfin-tvdb

    quality_definition:
      type: series

    quality_profiles:
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        reset_unmatched_scores:
          enabled: true
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        name: Remux-1080p - Anime # Override name to match old naming
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 3bc5f395426614e155e585a2f056cdf1 # Season Packs
        assign_scores_to:
          - name: WEB-1080p
          - name: Remux-1080p - Anime
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10000
      - trash_ids:
          - 9c14d194486c4014d422adc64092d794 # Dubs Only
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 5000

radarr:
  movies-1080p:
    base_url: http://radarr.home-media.svc.cluster.local:8080
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      folder: jellyfin-imdb
      movie:
        rename: true
        standard: jellyfin-imdb

    quality_definition:
      type: movie

    quality_profiles:
      - trash_id: 9ca12ea80aa55ef916e3751f4b874151 # Remux + WEB 1080p
        reset_unmatched_scores:
          enabled: true
      - trash_id: 722b624f9af1e492284c4bc842153a38 # Remux-1080p - Anime
        name: Remux-1080p - Anime # Override name to match old naming
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      - trash_ids:
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
        assign_scores_to:
          - name: Remux + WEB 1080p
          - name: Remux-1080p - Anime
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10000
      - trash_ids:
          - b23eae459cc960816f2d6ba84af45055 # Dubs Only
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 5000
