---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.home-media.svc.cluster.local:8080
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
    custom_formats:
      # WEB 1080p
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # Enable x265 for WEB-1080p and Remux-1080p - Anime
        assign_scores_to:
          - name: WEB-1080p
            score: 0
          - name: Remux-1080p - Anime
            score: 0
      # Prioritize dubs for anime (dual audio is of the highest preference)
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10000
      - trash_ids:
          - 9c14d194486c4014d422adc64092d794 # Dubs Only
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 5000

radarr:
  radarr:
    base_url: http://radarr.home-media.svc.cluster.local:8080
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-remux-web-1080p
      - template: radarr-custom-formats-remux-web-1080p
      - template: radarr-quality-definition-anime
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
    custom_formats:
      # Audio
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
        assign_scores_to:
          - name: Remux + WEB 1080p
      - trash_ids:
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: Remux + WEB 1080p
            score: 0
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: Remux + WEB 1080p
      # Prioritize dubs for anime (dual audio is of the highest preference)
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10000
      - trash_ids:
          - b23eae459cc960816f2d6ba84af45055 # Dubs Only
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 5000
