---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-backend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: private-backend
  template:
    metadata:
      labels:
        app: private-backend
    spec:
      containers:
        - name: flood
          image: ghcr.io/2024-cmpu9010-group-3/backend-private:0.2.0
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: LOGIN
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: LOGIN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: DATABASE_NAME
