---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./shelfmark/install.yaml
  - ./audiobookshelf/install.yaml
  - ./booklore/install.yaml
  - ./libation/install.yaml
  - ./opds-proxy/install.yaml
