---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solonsstuff-com
spec:
  secretName: solonsstuff-com-live-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: solonsstuff.com
  dnsNames: ["solonsstuff.com", "*.solonsstuff.com"]
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "nginx, networking"
