apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1FABU2g2L8znlZbTzPgPI/BHTg==,iv:16Kwieb5o6x0wMaQOhK3iYNz0RWAvM7rLLevmgz36ag=,tag:xEyR3/Rk6RsDBO/o06JJXQ==,type:str]
sops:
    age:
        - recipient: age13arp4yu8k7s9ck59ryj4vzedkggkp8eph6hq9ukdtcpdvnf8f9uqypjty6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSVlRMElweEZpTEg2UFQx
            Q3BqcktXNEc4cGkzN1BYRFZ3VUFhbE1Hb1ZRCmdEbmFCakFIdE9IOVN2MGhHQi9Z
            UFhmZGVvWDdRN004UG1TdU9nL3JhQVkKLS0tICs4VkJSQUdhYk01Ynk1NkNFRm9H
            UGY2b2hBVjlrQjkxV2lGSzhiSWVodU0KX66DfEqVuwWetGunyl0SGUdnNR+NuhNT
            GwX7CQggnQNhSnDmqHeDYBiDRqH/IhRft5ekoJPTTiSn2z3BIxWlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T14:09:44Z"
    mac: ENC[AES256_GCM,data:T/7f2+dvja5kfPku3nST9WL7NGazK55xFebQz1ZOjTxToQ/hAQ4I9tfmea9MpwjdJvekMY4VoKrfcmve8CYGEAtTqreB1c/NRBfouDFonoOeKsHS7ic8ew3sjkGgU2cG/cuq3A2GQsLeGj0L9jcEUm6NODxKySoN6+U17YG8xI8=,iv:xw8WJjaUVJZ3mG6QkVZMz0E7ptDnAzHiQ4kPQ/xHLYM=,tag:TrhuY2Kjk1gQ+q6A36VzpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
