apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hyXDPx2OU4Y30/ZbDn25j4C03h27Yid6FAZEmwZjzGN7cR6rYTrGpw==,iv:kA3hiTnjNO5vcqZt5aIOMkBLzsG0HmSmlLn1HEoogxc=,tag:3V8HNPN2Uq9PAekI417rTg==,type:str]
sops:
    age:
        - recipient: age13arp4yu8k7s9ck59ryj4vzedkggkp8eph6hq9ukdtcpdvnf8f9uqypjty6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSVlRMElweEZpTEg2UFQx
            Q3BqcktXNEc4cGkzN1BYRFZ3VUFhbE1Hb1ZRCmdEbmFCakFIdE9IOVN2MGhHQi9Z
            UFhmZGVvWDdRN004UG1TdU9nL3JhQVkKLS0tICs4VkJSQUdhYk01Ynk1NkNFRm9H
            UGY2b2hBVjlrQjkxV2lGSzhiSWVodU0KX66DfEqVuwWetGunyl0SGUdnNR+NuhNT
            GwX7CQggnQNhSnDmqHeDYBiDRqH/IhRft5ekoJPTTiSn2z3BIxWlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T14:33:43Z"
    mac: ENC[AES256_GCM,data:tZC4liUleuhSeIMgeO88r+dgZ3DHPC5dQysW0FsRfL9TCHM4xXv/lC4Xftz9NwUzvSX30KeCs/G3MlMCVNPFo3YvHgH2oGMEL/Nmfrk0PbYd2/Zna3+5lFl3JOhMiFqGXg8jvvHmf9Pv3ONaAyg4rcmnYjXexiWfac1dvWOuvjk=,iv:gaA+4g/KucFRTpMxSxfEwJMZnQ4fa8eYDoRCCEDwT3E=,tag:r6a/dEHvlC9DRBV6QV9C8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
