---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: chrisms-garage.tail9542f6.ts.net
  name: chrisms-garage
spec:
  externalName: chrisms-garage    # any value - will be overwritten by operator
  type: ExternalName
