---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-vars.yaml
- apps
- games
- observability
- infra
- networking
- storage
- nodes
- security
- media
- projects
- manga
- ai