---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    template:
      data:
        # LiteLLM
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}" # Must start with sk-
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}" # Must start with sk-
        UI_USERNAME: "{{ .LITELLM_UI_USERNAME }}"
        UI_PASSWORD: "{{ .LITELLM_UI_PASSWORD }}"

        # AI APIs
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        GOOGLE_API_KEY: "{{ .GOOGLE_API_KEY }}"

  dataFrom:
    - extract:
        key: ai-api-keys
    - extract:
        key: litellm

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: litellm-db-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: '{{ index . "uri" }}'

  dataFrom:
    - extract:
        key: postgres-pguser-litellm